siyi_rtsp_publisher:
  ros__parameters:
    rtsp_url: "rtsp://192.168.168.16:8554/main.264"
    frame_id: "siyi_camera_optical_frame"
    flip_180: false
    target_fps: 30.0
    image_width: 1280
    image_height: 720
    camera_fx: 733.95577
    camera_fy: 735.28401
    camera_cx: 654.37518
    camera_cy: 352.23005
    camera_d: [-0.119821, 0.087530, -0.007342, -0.002788, 0.0]
