cmake_minimum_required(VERSION 3.8)
project(dib_domain_bridge)
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 17)
endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(domain_bridge REQUIRED)
find_package(dib_msgs REQUIRED)
add_executable(dib_split_bridge src/dib_split_bridge.cpp)
ament_target_dependencies(dib_split_bridge rclcpp domain_bridge dib_msgs)
install(TARGETS dib_split_bridge DESTINATION lib/${PROJECT_NAME})
ament_package()
